python test.py --model Unet \
            --dataset paris \
            --checkpoint ./checkpoints/20210529_paris_100_ft/50.pt \
            --seq_path ./output/ \
            --image_dir dataset/paris/ \
            --image_list_train namelist/paris_training.txt \
            --image_list_test namelist/paris_testing.txt \
            --mask_dir dataset/mask/testing_mask_dataset/ \
            --mask_list_train namelist/nv_mask_training.txt \
            --mask_list_test namelist/nv_mask_testing.txt \
            --show_ratio 10
